src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Discount_if_applicable_Dollar__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is for employee referral</description>
        <label>$ Discount (if applicable)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discount_if_applicable__c</fullName>
        <defaultValue>0</defaultValue>
        <label>% Discount (if applicable)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Freight_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Freight Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Freight_Refund__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Freight Refund</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Internal_Contact1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Contact1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Internal_Contact2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is for internal sales rep and managers</description>
        <label>Internal Contact2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Internal_Contact3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is for internal sales rep and managers</description>
        <label>Internal Contact3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Internal_Contact4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Contact4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Cost__c</fullName>
        <label>Product Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Group__c</fullName>
        <label>Service Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Special Services</fullName>
                </value>
                <value>
                    <fullName>East</fullName>
                </value>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
                <value>
                    <fullName>ASI</fullName>
                </value>
                <value>
                    <fullName>Inside</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <formula>Total_Order__c  -  Total_Merchandise__c  -  Freight_Amount__c  -  Freight_Tax__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Merchandise Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Merchandise__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Merchandise</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Tax_Refund__c</fullName>
        <label>Total Tax Refund</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Discount_if_applicable_Dollar__c</fullName>
        <defaultValue>0</defaultValue>
        <label>$ Discount (if applicable)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discount_if_applicable__c</fullName>
        <defaultValue>0</defaultValue>
        <label>% Discount (if applicable)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Cost__c</fullName>
        <label>Product Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <formula>(Case__r.Tax__c  /  Case__r.Total_Merchandise__c ) *  Product_Cost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tax__c.object
<CustomObject>
    <label>Tax</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Tax Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseordeitemTest.cls
@isTest
public class CaseordeitemTest{
  
    @isTest
    public static void testCaseTrigger(){
    
        Id devRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Brand Management').getRecordTypeId();
        
        Account objAccount = new Account();
        objAccount.Name = 'Test Acc';
        insert objAccount;
        
        Contact con = new Contact();
        con.LastName = 'Test';
        con.AccountId = objAccount.id;
        con.Email = 'Test@gmail.com';
        Insert con;
        
       
        Case objCase = new Case();
        objCase.Subject = 'Test';
        objCase.recordTypeId = devRecordTypeId ;
        objCase.Status = 'New';
        objCase.Type = 'Sales';
        objCase.ContactId = con.Id;
        objCase.Internal_Contact1__c = UserInfo.getUserId();
        objCase.Internal_Contact2__c = UserInfo.getUserId();
        objCase.Internal_Contact3__c = UserInfo.getUserId();
        objCase.Internal_Contact4__c = UserInfo.getUserId();
        objCase.Service_Group__c = 'Canada';
        objCase.Freight_Refund__c  = true;
        objCase.Freight_Amount__c  = 10;
        objCase.Total_Tax_Refund__c  = 50;
        objCase.Discount_if_applicable_Dollar__c  = 5;
        
        objCase.Total_Merchandise__c  = 10;
        
        insert  objCase;
        
        Order_Item__c  or1 = new Order_Item__c();
        or1.Case__c = objCase.id;
        or1.Product_Cost__c= 10;
       // or1.Tax__c = 2;
        insert or1;
        
        update or1;
         objCase.Discount_if_applicable_Dollar__c  = null;
        objCase.Discount_if_applicable__c  = 1;
        update objCase;
                                   
        
      
    }
}