src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Discount_if_applicable_Dollar__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is for employee referral</description>
        <label>$ Discount (if applicable)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Freight_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Freight Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Freight_Refund__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Freight Refund</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Freight_Tax__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Freight Tax</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <formula>Total_Order__c  -  Total_Merchandise__c  -  Freight_Amount__c  -  Freight_Tax__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Merchandise Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Merchandise__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Merchandise</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Order__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Order</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Refund__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Refund</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Tax_Refund__c</fullName>
        <label>Total Tax Refund</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Discount_if_applicable_Dollar__c</fullName>
        <defaultValue>0</defaultValue>
        <label>$ Discount (if applicable)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <formula>(Case__r.Tax__c  /  Case__r.Total_Merchandise__c ) *  Product_Cost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tax__c.object
<CustomObject>
    <label>Tax</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Tax Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderItemTriggerHelper.cls
public class OrderItemTriggerHelper{


public static void afterUpdate(list<Order_Item__c> oitemlist){
   set<id> caseids = new set<id>();
   for(Order_Item__c oi: oitemlist){
    caseids.add(oi.Case__c);
   }
   if(caseids.size()>0){
   list<case> cslist = new list<case>();
   cslist = [select id,Total_Refund__c ,Total_Tax_Refund__c, Freight_Refund__c ,Freight_Amount__c ,Freight_Tax__c,Discount_if_applicable_Dollar__c ,Total_Merchandise__c ,Total_Order__c ,Tax__c from case where id in: caseids ];
   CaseDiscountCalculations.CalculateTotalRefund(cslist, true);
   }
}

}