src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Discount_if_applicable_Dollar__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is for employee referral</description>
        <label>$ Discount (if applicable)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discount_if_applicable__c</fullName>
        <defaultValue>0</defaultValue>
        <label>% Discount (if applicable)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Freight_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Freight Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Freight_Refund__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Freight Refund</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Freight_Tax__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Freight Tax</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Cost__c</fullName>
        <label>Product Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <formula>Total_Order__c  -  Total_Merchandise__c  -  Freight_Amount__c  -  Freight_Tax__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Merchandise Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Merchandise__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Merchandise</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Order__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Order</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Refund__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Refund</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Tax_Refund__c</fullName>
        <label>Total Tax Refund</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Discount_if_applicable_Dollar__c</fullName>
        <defaultValue>0</defaultValue>
        <label>$ Discount (if applicable)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discount_if_applicable__c</fullName>
        <defaultValue>0</defaultValue>
        <label>% Discount (if applicable)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Cost__c</fullName>
        <label>Product Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <formula>(Case__r.Tax__c  /  Case__r.Total_Merchandise__c ) *  Product_Cost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tax__c.object
<CustomObject>
    <label>Tax</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Tax Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseDiscountCalculations.cls
public class CaseDiscountCalculations{

  
     public static void CalculateTotalRefund(List<Case> newCase, boolean isorderitem){
      set<id> caseids = new set<id>();
          for(Case objCase : newCase){
          caseids.add(objCase.id);
        }
      
      

        Map<string,decimal> caseIDvtAmount = new Map<string,decimal>();

         Map<string,decimal> caseIDvtTax = new Map<string,decimal>();

        for(Order_Item__c  ss :  [select id,Case__r.id,Product_Cost__c,Tax__c,Discount_if_applicable__c,Discount_if_applicable_Dollar__c from Order_Item__c where Case__r.id in :caseids]){
           

                if (! caseIDvtAmount.containsKey(ss.Case__r.id)) {
                  caseIDvtAmount.put(ss.Case__r.id,0);                   
                }
                caseIDvtAmount.put(ss.Case__r.id,caseIDvtAmount.get(ss.Case__r.id) + ss.Tax__c + ss.Product_Cost__c);
                
                
                 if (! caseIDvtTax.containsKey(ss.Case__r.id)) {
                  caseIDvtTax.put(ss.Case__r.id,0);                   
                }
                caseIDvtTax.put(ss.Case__r.id,caseIDvtTax.get(ss.Case__r.id) + ss.Tax__c );
            
        }
        
         system.debug('caseIDvtAmount------------- ' + caseIDvtAmount); 
       list<case> casetoUpd = new list<case>();
         for(Case objCase : newCase){
         if(caseIDvtAmount.get(objCase.id) != null){
         objCase.Total_Refund__c = caseIDvtAmount.get(objCase.id);
         }else{
         objCase.Total_Refund__c = 0;
         }
         if(caseIDvtTax.get(objCase.id) != null){
         objCase.Total_Tax_Refund__c = caseIDvtTax.get(objCase.id);
         }else{
         objCase.Total_Tax_Refund__c = 0;
         }
         
          if(objCase.Freight_Refund__c == true){
             objCase.Total_Refund__c += objCase.Freight_Amount__c + objCase.Freight_Tax__c;
             objCase.Total_Tax_Refund__c += objCase.Freight_Tax__c;
             }
             
          if(objCase.Discount_if_applicable_Dollar__c != null){
            //objCase.Total_Tax_Refund__c += objCase.Discount_if_applicable_Dollar__c;
            objCase.Total_Refund__c  += objCase.Discount_if_applicable_Dollar__c;
          }  
          
          if(objCase.Discount_if_applicable__c != null){ //merchandise refund
             objCase.Total_Refund__c += ((objCase.Total_Merchandise__c * objCase.Discount_if_applicable__c)/100);     
             objCase.Total_Tax_Refund__c += ((objCase.Tax__c * objCase.Discount_if_applicable__c)/100);  
          } 
         /*  if(objCase.Discount_if_applicable__c != null){ //order refund
             objCase.Total_Refund__c += ((objCase.Total_Order__c * objCase.Discount_if_applicable__c)/100);      
          }*/
           if(objCase.Discount_if_applicable_Dollar__c != null){ // tax refund
            objCase.Total_Refund__c += ((objCase.Tax__c / objCase.Total_Merchandise__c ) * objCase.Discount_if_applicable_Dollar__c);   
              objCase.Total_Tax_Refund__c += ((objCase.Tax__c / objCase.Total_Merchandise__c ) * objCase.Discount_if_applicable_Dollar__c);   
          }
         
          casetoUpd.add(objCase);
        }
        
        if(isorderitem == true && casetoUpd.size()>0){
          update casetoUpd;
        }
       
     }
    
}