src/objects/CategoryManagement__mdt.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ischecked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ischecked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <label>Material</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CategoryManagement</label>
    <pluralLabel>CategoryManagements</pluralLabel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <description>This field is for Industrial team</description>
        <label>Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tops</fullName>
                    <label>First Layer Tops</label>
                </value>
                <value>
                    <fullName>Bottoms</fullName>
                    <label>First Layer Bottoms</label>
                </value>
                <value>
                    <fullName>Outerwear</fullName>
                </value>
                <value>
                    <fullName>Accessories</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <label>Material</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>100234-051</fullName>
                </value>
                <value>
                    <fullName>100234-410</fullName>
                </value>
                <value>
                    <fullName>100235-051</fullName>
                </value>
                <value>
                    <fullName>100235-250</fullName>
                </value>
                <value>
                    <fullName>100235-410</fullName>
                </value>
                <value>
                    <fullName>100235-465</fullName>
                </value>
                <value>
                    <fullName>100237-051</fullName>
                </value>
                <value>
                    <fullName>100237-250</fullName>
                </value>
                <value>
                    <fullName>100237-410</fullName>
                </value>
                <value>
                    <fullName>100237-465</fullName>
                </value>
                <value>
                    <fullName>100410-001</fullName>
                </value>
                <value>
                    <fullName>100410-026</fullName>
                </value>
                <value>
                    <fullName>100410-034</fullName>
                </value>
                <value>
                    <fullName>100410-316</fullName>
                </value>
                <value>
                    <fullName>100410-412</fullName>
                </value>
                <value>
                    <fullName>100432-001</fullName>
                </value>
                <value>
                    <fullName>100432-201</fullName>
                </value>
                <value>
                    <fullName>100432-316</fullName>
                </value>
                <value>
                    <fullName>100493-824</fullName>
                </value>
                <value>
                    <fullName>100493-323</fullName>
                </value>
                <value>
                    <fullName>100494-824</fullName>
                </value>
                <value>
                    <fullName>100494-323</fullName>
                </value>
                <value>
                    <fullName>100495-323</fullName>
                </value>
                <value>
                    <fullName>100495-824</fullName>
                </value>
                <value>
                    <fullName>100496-323</fullName>
                </value>
                <value>
                    <fullName>100496-824</fullName>
                </value>
                <value>
                    <fullName>100499-323</fullName>
                </value>
                <value>
                    <fullName>100501-323</fullName>
                </value>
                <value>
                    <fullName>100501-824</fullName>
                </value>
                <value>
                    <fullName>100503-323</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MultiselectController.cls
global class MultiselectController {
    
    @Auraenabled
    public static List<MultiSelectControllerWrapper> getAccountName(String recordId){
        List<MultiSelectControllerWrapper> listMultiSelectControllerWrapper = new List<MultiSelectControllerWrapper>();
        Opportunity opp = [SELECT ID,Material__c,Category__c from  Opportunity WHERE ID =:recordId];
        Set<String> selectedCategory = new Set<String>();
        if(opp.Category__c != null)
        selectedCategory.addAll(opp.Category__c.split(';'));
        Set<CategoryManagement__mdt> acclist = new Set<CategoryManagement__mdt>();
        Set<String> uniquecategory = new Set<string>();
        List<CategoryManagement__mdt> uniqueAcclist = new List<CategoryManagement__mdt>();
        CategoryManagement__mdt[] CategoryManagement = [SELECT MasterLabel,Category__c,Material__c,Ischecked__c FROM CategoryManagement__mdt];
        for(CategoryManagement__mdt objAccount : CategoryManagement){
           MultiSelectControllerWrapper objMultiSelectControllerWrapper = new MultiSelectControllerWrapper(); 
            if(!uniquecategory.Contains(objAccount.Category__c)){
                    objMultiSelectControllerWrapper.objCategoryMangement = objAccount;
                objMultiSelectControllerWrapper.isSelected = false; 
                if(selectedCategory.contains(objAccount.Category__c)){
                    objMultiSelectControllerWrapper.isSelected = true;     
                }
                uniquecategory.add(objAccount.Category__c); 
                listMultiSelectControllerWrapper.add(objMultiSelectControllerWrapper);
            }
            
        }
        
        return listMultiSelectControllerWrapper;
    }
    
    @Auraenabled
    public static List<MultiSelectControllerWrapper> getMaterialOnload(String recordId){
        List<MultiSelectControllerWrapper> listMultiSelectControllerWrapper = new List<MultiSelectControllerWrapper>();
        Opportunity opp = [SELECT ID,Material__c,Category__c from  Opportunity WHERE ID=:recordId];
        Set<String> selectedCategory = new Set<String>();
        Set<String> selectedMaterial = new Set<String>(); 
        if(opp.Material__c != null)
        selectedMaterial.addAll(opp.Material__c.split(';'));
        if(opp.Category__c != null)
        selectedCategory.addAll(opp.Category__c.split(';'));
        
        
        Set<CategoryManagement__mdt> acclist = new Set<CategoryManagement__mdt>();
        Set<String> uniquecategory = new Set<string>();
        List<CategoryManagement__mdt> uniqueAcclist = new List<CategoryManagement__mdt>();
        CategoryManagement__mdt[] CategoryManagement = [SELECT MasterLabel,Category__c,Material__c,Ischecked__c FROM CategoryManagement__mdt];
        for(CategoryManagement__mdt objAccount : CategoryManagement){
           
            if(!uniquecategory.Contains(objAccount.Material__c) && selectedCategory.contains(objAccount.Category__c) ){
                MultiSelectControllerWrapper objMultiSelectControllerWrapper = new MultiSelectControllerWrapper(); 
                objMultiSelectControllerWrapper.objCategoryMangement = objAccount;
                objMultiSelectControllerWrapper.isSelected = false; 
                if(selectedMaterial.contains(objAccount.Material__c))
                {
                    objMultiSelectControllerWrapper.isSelected = true; 
                    uniquecategory.add(objAccount.Material__c);  
                }
                
                listMultiSelectControllerWrapper.add(objMultiSelectControllerWrapper);
                }

        }
        
        return listMultiSelectControllerWrapper;
    }
    
     @Auraenabled
    public static List<MultiSelectControllerWrapper> getContact( String material){
        List<MultiSelectControllerWrapper> listMultiSelectControllerWrapper = new List<MultiSelectControllerWrapper>();
        
        CategoryManagement__mdt[] CategoryManagement = [SELECT MasterLabel,Category__c,Material__c FROM CategoryManagement__mdt Where Category__c =:material];
        for(CategoryManagement__mdt objAccount : CategoryManagement){
            MultiSelectControllerWrapper objMultiSelectControllerWrapper = new MultiSelectControllerWrapper(); 
            objMultiSelectControllerWrapper.objCategoryMangement = objAccount;
            objMultiSelectControllerWrapper.isSelected = false; 
            listMultiSelectControllerWrapper.add(objMultiSelectControllerWrapper);
        }
        return listMultiSelectControllerWrapper;
    }
    
    @Auraenabled
    public static void saveMaterial( String materialString,String listCategory,String recordId){
        
        System.debug('materialString>>>>'+materialString);
        Opportunity opp = [SELECT ID,Material__c,Category__c from  Opportunity WHERE ID =: recordId];
        opp.Material__c  = materialString;
        opp.Category__c  = listCategory;
        Update opp;
    }

}