src/objects/CategoryManagement__mdt.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <label>Material</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CategoryManagement</label>
    <pluralLabel>CategoryManagements</pluralLabel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <description>This field is for Industrial team</description>
        <label>Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tops</fullName>
                    <label>First Layer Tops</label>
                </value>
                <value>
                    <fullName>Bottoms</fullName>
                    <label>First Layer Bottoms</label>
                </value>
                <value>
                    <fullName>Outerwear</fullName>
                </value>
                <value>
                    <fullName>Accessories</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <label>Material</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>100234-051</fullName>
                </value>
                <value>
                    <fullName>100234-410</fullName>
                </value>
                <value>
                    <fullName>100235-051</fullName>
                </value>
                <value>
                    <fullName>100235-250</fullName>
                </value>
                <value>
                    <fullName>100235-410</fullName>
                </value>
                <value>
                    <fullName>100235-465</fullName>
                </value>
                <value>
                    <fullName>100237-051</fullName>
                </value>
                <value>
                    <fullName>100237-250</fullName>
                </value>
                <value>
                    <fullName>100237-410</fullName>
                </value>
                <value>
                    <fullName>100237-465</fullName>
                </value>
                <value>
                    <fullName>100410-001</fullName>
                </value>
                <value>
                    <fullName>100410-026</fullName>
                </value>
                <value>
                    <fullName>100410-034</fullName>
                </value>
                <value>
                    <fullName>100410-316</fullName>
                </value>
                <value>
                    <fullName>100410-412</fullName>
                </value>
                <value>
                    <fullName>100432-001</fullName>
                </value>
                <value>
                    <fullName>100432-201</fullName>
                </value>
                <value>
                    <fullName>100432-316</fullName>
                </value>
                <value>
                    <fullName>100493-824</fullName>
                </value>
                <value>
                    <fullName>100493-323</fullName>
                </value>
                <value>
                    <fullName>100494-824</fullName>
                </value>
                <value>
                    <fullName>100494-323</fullName>
                </value>
                <value>
                    <fullName>100495-323</fullName>
                </value>
                <value>
                    <fullName>100495-824</fullName>
                </value>
                <value>
                    <fullName>100496-323</fullName>
                </value>
                <value>
                    <fullName>100496-824</fullName>
                </value>
                <value>
                    <fullName>100499-323</fullName>
                </value>
                <value>
                    <fullName>100501-323</fullName>
                </value>
                <value>
                    <fullName>100501-824</fullName>
                </value>
                <value>
                    <fullName>100503-323</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OpportunityTriggerHandler.cls
public class OpportunityTriggerHandler {
 public static void beforeInsertUpdate(List<Opportunity> newOpportunities){
     Map<String,List<String>> mapCategoryManagement = new Map<String,List<String>>();
        CategoryManagement__mdt[] CategoryManagement = [SELECT MasterLabel,Category__c,Material__c FROM CategoryManagement__mdt];
        for(CategoryManagement__mdt objCategoryManagement : CategoryManagement){
            if(!mapCategoryManagement.containsKey(objCategoryManagement.Category__c))
                mapCategoryManagement.put(objCategoryManagement.Category__c,new List<String>{objCategoryManagement.Material__c});
            else
                mapCategoryManagement.get(objCategoryManagement.Category__c).add(objCategoryManagement.Material__c);
        }
        for(Opportunity opp: newOpportunities){
            if(opp.Category__c != null)
            {
                List<String> Categories = opp.Category__c.split(';');
            List<String> materialList = new List<String>();
            for(String objCategory : Categories ){
                if(mapCategoryManagement.containsKey(objCategory))
                materialList.addall(mapCategoryManagement.get(objCategory));
            }
            opp.Material__c = string.join(materialList,';'); 
            }
            
        }

     
 }
}