src/objects/Customer_E_Receipts__c.object
<CustomObject>
    <fields>
        <fullName>Barcode__c</fullName>
        <label>Barcode</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DeviceId__c</fullName>
        <description>This identifies the device where the transaction was done</description>
        <label>DeviceId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalespersonId__c</fullName>
        <description>Sales Person associasted with the item</description>
        <label>SalespersonId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesperson_Name__c</fullName>
        <description>Sales Person associasted with the item</description>
        <label>Salesperson Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Customer E-Receipts</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>E-Receipts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer E-Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TransactionItem__c.object
<CustomObject>
    <fields>
        <fullName>E_Receipts_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>E-Receipts Number</label>
        <referenceTo>Customer_E_Receipts__c</referenceTo>
        <relationshipLabel>TransactionItems</relationshipLabel>
        <relationshipName>TransactionItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promotions_Name__c</fullName>
        <description>Name of the promotion</description>
        <label>Promotions Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TaxRate_Percentage__c</fullName>
        <description>The actual tax rate</description>
        <label>TaxRate Percentage</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>TransactionItem</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>TransactionItem Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TransactionItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sendRequestToMarketingCloudTests.cls
@isTest
private class sendRequestToMarketingCloudTests{
  /**  @isTest static void testCalloutWithStaticResources() {
       
       Customer_E_Receipts__c CE = New Customer_E_Receipts__c();
       CE.DeviceId__c = 'VarunDevice';
       CE.SalespersonId__c= 'Text';
       CE.Salesperson_Name__c = 'Varun';
       Insert CE;
       
       TransactionItem__c TI = New TransactionItem__c();
      // TI.Barcode__c= 'Code';
      // TI.E_Receipts_Number__c = CE.Id;
    //  TI.Description__c= 'large';
     //  TI.ProductType__c= 'Shirt3';
     //  TI.Sku__c = 'Shirt';
    //   TI.Promotions_Name__c = 'Shirt2';
     //  TI.TaxRate_Percentage__c = 'Shirt4';
      // Insert TI;
       
       
       MockHttpResponseGenerator.jsonResponse = '{"accessToken": "1XlFsRKjGCXqK1rZmHftV68Y","expiresIn": 3479}';
       Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
       //As Per Best Practice it is important to instantiate the Rest Context 
       StaticResource  objStaticResource =  [Select body, name from StaticResource where Name = 'MarketingCloudJson']; 
       Test.startTest();
       RestRequest req = new RestRequest(); 
       RestResponse res = new RestResponse();
             
       req.requestURI = 'https://uat1-carharttars.cs20.force.com/Ideasthatwork/services/apexrest/marketingCloud/';  //Request URL
       req.httpMethod = 'POST';//HTTP Request Type
       req.requestBody = objStaticResource.body ;
       RestContext.request = req;
       RestContext.response= res;
       
       MarketingCloudController.responseWrapper resp = new  MarketingCloudController.responseWrapper (); 
       resp = MarketingCloudController.MarketingCloudInput(); //Call the Method of the Class with Proper Constructor 
       
      Test.stopTest(); 
        
} **/
}