src/objects/Customer_E_Receipts__c.object
<CustomObject>
    <fields>
        <fullName>Barcode__c</fullName>
        <label>Barcode</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cash_Amount__c</fullName>
        <description>Amount defines the total price or amount customer owes the business.</description>
        <label>Cash Amount</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cashier_userFirstName__c</fullName>
        <description>User first name</description>
        <label>Cashier userFirstName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cashier_userId__c</fullName>
        <description>UserId of the user that completed this action (cashier)</description>
        <label>Cashier userId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cashier_userLastName__c</fullName>
        <description>User last name</description>
        <label>User LastName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cashier_userName__c</fullName>
        <description>Username of the user that completed this action (cashier)</description>
        <label>Cashier userName</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CreditCard_Description__c</fullName>
        <description>Card Description used for card payment</description>
        <label>CreditCard Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrencyId__c</fullName>
        <label>CurrencyId</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerAddress__c</fullName>
        <label>CustomerAddress</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CustomerCity__c</fullName>
        <label>CustomerCity</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerEmail__c</fullName>
        <label>CustomerEmail</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerFirstName__c</fullName>
        <label>CustomerFirstName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerHomePhoneNumber__c</fullName>
        <label>CustomerHomePhoneNumber</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerLastName__c</fullName>
        <label>CustomerLastName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerMobilePhoneNumber__c</fullName>
        <label>CustomerMobilePhoneNumber</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerState__c</fullName>
        <label>CustomerState</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerWorkPhoneNumber__c</fullName>
        <label>CustomerWorkPhoneNumber</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerZipCode__c</fullName>
        <label>CustomerZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DiscountTotal__c</fullName>
        <label>DiscountTotal</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoyaltyPoints__c</fullName>
        <label>LoyaltyPoints</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loyalty_Email__c</fullName>
        <label>Loyalty Email</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Loyalty_FirstName__c</fullName>
        <label>Loyalty FirstName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loyalty_LastName__c</fullName>
        <label>Loyalty LastName</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Loyalty_MobilePhoneNumber__c</fullName>
        <label>Loyalty MobilePhoneNumber</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loyalty_Type__c</fullName>
        <label>Loyalty Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MerchTotal__c</fullName>
        <label>MerchTotal</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PromoTotal__c</fullName>
        <label>PromoTotal</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalespersonId__c</fullName>
        <description>Sales Person associasted with the item</description>
        <label>SalespersonId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesperson_Name__c</fullName>
        <description>Sales Person associasted with the item</description>
        <label>Salesperson Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SendData__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SendData</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StoreId__c</fullName>
        <description>StoreId for Store</description>
        <label>StoreId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store_City__c</fullName>
        <description>Store city</description>
        <label>Store City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store_Country__c</fullName>
        <description>Store Country</description>
        <label>Store Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store_FaxNumber__c</fullName>
        <description>Store Fax number</description>
        <label>Store FaxNumber</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store_Name__c</fullName>
        <description>Store Name</description>
        <label>Store Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store_PhoneNumber__c</fullName>
        <description>Store Phone Number</description>
        <label>Store PhoneNumber</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Store_TimeZone__c</fullName>
        <description>TimeZone</description>
        <label>Store TimeZone</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store_ZipCode__c</fullName>
        <description>Store Zip Code</description>
        <label>Store ZipCode</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <description>Store Street name</description>
        <label>Street Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Till_Id__c</fullName>
        <description>Id number of the till associated with the device</description>
        <label>Till Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalAmount__c</fullName>
        <label>TotalAmount</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalTaxValue__c</fullName>
        <label>TotalTaxValue</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Items__c</fullName>
        <label>Total Items</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Refund_Items__c</fullName>
        <label>Total Refund Items</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TransactionId__c</fullName>
        <label>TransactionId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>localTimeZone__c</fullName>
        <label>localTimeZone</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>localTranDate__c</fullName>
        <label>localTranDate</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>loyaltyId__c</fullName>
        <description>The ID number of the loyalty customer</description>
        <label>loyaltyId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>nonLoyaltyEmail__c</fullName>
        <label>NonLoyaltyEmail</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>payments__c</fullName>
        <label>payments</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>streetNumber__c</fullName>
        <description>Store Street number</description>
        <label>streetNumber</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tranDate__c</fullName>
        <label>tranDate</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tranItems__c</fullName>
        <label>tranItems</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tranNo__c</fullName>
        <label>tranNo</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tranTypeId__c</fullName>
        <label>tranTypeId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>transactionDiscounts__c</fullName>
        <label>transactionDiscounts</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Customer E-Receipts</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>E-Receipts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer E-Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tax__c.object
<CustomObject>
    <fields>
        <fullName>Customer_E_Receipts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer E-Receipts</label>
        <referenceTo>Customer_E_Receipts__c</referenceTo>
        <relationshipLabel>Taxes</relationshipLabel>
        <relationshipName>Taxes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaxID__c</fullName>
        <label>TaxID</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Tax_Description__c</fullName>
        <label>Tax Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_DisplayCode__c</fullName>
        <label>Tax DisplayCode</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Indicator__c</fullName>
        <label>Tax Indicator</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Total__c</fullName>
        <label>Tax Total</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Type__c</fullName>
        <label>Tax Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tax</fullName>
                </value>
                <value>
                    <fullName>NetTax</fullName>
                </value>
                <value>
                    <fullName>TaxExempt</fullName>
                </value>
                <value>
                    <fullName>TotalVAT</fullName>
                </value>
                <value>
                    <fullName>TotalAddOnVAT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tax</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Tax Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TransactionItem__c.object
<CustomObject>
    <fields>
        <fullName>E_Receipts_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>E-Receipts Number</label>
        <referenceTo>Customer_E_Receipts__c</referenceTo>
        <relationshipLabel>TransactionItems</relationshipLabel>
        <relationshipName>TransactionItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Barcode__c</fullName>
        <description>Product barcode associated with the SKU</description>
        <label>Transaction Barcode</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Description__c</fullName>
        <description>Product description</description>
        <label>Transaction Description</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Transaction_ItemName__c</fullName>
        <label>Transaction ItemName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_ProductType__c</fullName>
        <label>Transaction ProductType</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Sku__c</fullName>
        <description>Product SKU</description>
        <label>Transaction Sku</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>TransactionItem</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>TransactionItem Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TransactionItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MarketingCloudController.cls
@RestResource(urlMapping='/marketingCloud/*') //endpoint definition > {Salesforce Base URL}/services/apexrest/CreateLeadController/
global class MarketingCloudController {
    
    
    @HttpPost //HttpPost annotation exposes the method as a REST resource and called when an HTTP POST request is sent
    global static String MarketingCloudInput() {
        String message; 
        try{
        RestRequest req = RestContext.request; //the RestRequest for the Apex REST method
        Map<String, Object> body = new Map<String, Object>();
        String jsonBody = req.requestBody.toString(); //the body of the request
        Map<String, Object> jsonMap = (Map<String, Object>)JSON.deserializeUntyped(jsonBody);
        List<Customer_E_Receipts__c> listCustomerEReceipt = new List<Customer_E_Receipts__c>(); 
        Customer_E_Receipts__c objCustomerEReceipt = new Customer_E_Receipts__c();
        
        
        // Required fields 
        message = 'Success ->'+ (String)jsonMap.get('id');
        objCustomerEReceipt.Till_Id__c = (String)jsonMap.get('tillId');  
        objCustomerEReceipt.MerchTotal__c = (String)jsonMap.get('merchTotal');
        objCustomerEReceipt.TotalAmount__c = (String)jsonMap.get('total');
        objCustomerEReceipt.StoreId__c = (String)jsonMap.get('storeId');
        objCustomerEReceipt.Store_Name__c = (String)jsonMap.get('storeName');
        objCustomerEReceipt.Street_Name__c = (String)jsonMap.get('streetName');
        objCustomerEReceipt.streetNumber__c = (String)jsonMap.get('streetNumber');
        objCustomerEReceipt.Store_City__c = (String)jsonMap.get('storeCity');
        objCustomerEReceipt.Store_ZipCode__c = (String)jsonMap.get('storeZipCode');
        objCustomerEReceipt.Store_Country__c = (String)jsonMap.get('storeCountry');
        objCustomerEReceipt.Store_PhoneNumber__c = (String)jsonMap.get('storePhoneNumber');
        objCustomerEReceipt.Store_FaxNumber__c = (String)jsonMap.get('storeFaxNumber');
        objCustomerEReceipt.Store_TimeZone__c = (String)jsonMap.get('storeTimeZone');
        objCustomerEReceipt.tranNo__c = string.valueof((Integer)jsonMap.get('tranNo'));
        objCustomerEReceipt.Barcode__c = (String)jsonMap.get('barcode');
        objCustomerEReceipt.tranTypeId__c = (String)jsonMap.get('tranTypeId');
        objCustomerEReceipt.tranDate__c = (String)jsonMap.get('tranDate');
        objCustomerEReceipt.localTranDate__c = (String)jsonMap.get('localTranDate');
        objCustomerEReceipt.localTimeZone__c = (String)jsonMap.get('localTimeZone');
        objCustomerEReceipt.Total_Items__c = string.valueof((Integer)jsonMap.get('totalItems'));
        objCustomerEReceipt.PromoTotal__c = (String)jsonMap.get('promoTotal');
        objCustomerEReceipt.CustomerFirstName__c = (String)jsonMap.get('customerFirstName');
        objCustomerEReceipt.CustomerLastName__c = (String)jsonMap.get('customerLastName');
        objCustomerEReceipt.CustomerAddress__c = (String)jsonMap.get('customerAddress1');
        objCustomerEReceipt.CustomerCity__c = (String)jsonMap.get('customerCity');
        objCustomerEReceipt.CustomerState__c = (String)jsonMap.get('customerState');
        objCustomerEReceipt.CustomerZipCode__c = (String)jsonMap.get('customerZipCode');
        objCustomerEReceipt.CustomerEmail__c = (String)jsonMap.get('customerEmail');
        objCustomerEReceipt.CustomerMobilePhoneNumber__c = (String)jsonMap.get('customerMobilePhoneNumber');
        objCustomerEReceipt.CustomerHomePhoneNumber__c = (String)jsonMap.get('customerHomePhoneNumber');
        objCustomerEReceipt.CustomerWorkPhoneNumber__c = (String)jsonMap.get('customerWorkPhoneNumber');
        objCustomerEReceipt.Total_Refund_Items__c = string.valueof((Integer)jsonMap.get('totalRefundItems'));
        objCustomerEReceipt.nonLoyaltyEmail__c = (String)jsonMap.get('nonLoyaltyEmail');
        objCustomerEReceipt.LoyaltyPoints__c = (String)jsonMap.get('loyaltyPoints');
        
        
        
        
        
        // Not Required fields
        
        objCustomerEReceipt.SalespersonId__c = (String)jsonMap.get('salespersonId');
        objCustomerEReceipt.Salesperson_Name__c = (String)jsonMap.get('salespersonName');
        objCustomerEReceipt.Cashier_userId__c = (String)jsonMap.get('userId');
        objCustomerEReceipt.Cashier_userName__c = (String)jsonMap.get('userName');
        objCustomerEReceipt.Cashier_userFirstName__c = (String)jsonMap.get('userFirstName');
        objCustomerEReceipt.Cashier_userLastName__c = (String)jsonMap.get('userLastName');
        objCustomerEReceipt.CurrencyId__c = (String)jsonMap.get('currencyId');
        objCustomerEReceipt.DiscountTotal__c = (String)jsonMap.get('discountTotal');
        objCustomerEReceipt.TotalTaxValue__c = (String)jsonMap.get('totalTaxValue');
        
        
        //  message = (String)jsonMap.get('taxExempt'); 
        // objCustomerEReceipt.TransactionId__c = (integer)jsonMap.get('transactionId'); -------------------------------- causing issue
        // objCustomerEReceipt.tranItems__c = (String)jsonMap.get('tranItems');
        // objCustomerEReceipt.payments__c = (String)jsonMap.get('payments');
        //  objCustomerEReceipt.transactionDiscounts__c = (String)jsonMap.get('transactionDiscounts');
        
        
        
        //objCustomerEReceipt.CustomerEmail__c = 'Test@gmail.com';
        //objCustomerEReceipt.nonLoyaltyEmail__c = 'Test@gmail.com';
        
        
        
        
        
        
        
        // Loyalty User details 
        
        List<Object> listLoyaltyUser = (List<Object>) jsonMap.get('loyaltyUser');
        if(listLoyaltyUser != null)
        Map<String,object> mapLoyaltyUserJSON = (Map<String,object>)listLoyaltyUser[0];
        
        objCustomerEReceipt.loyaltyId__c = (String)jsonMap.get('loyaltyId');
        objCustomerEReceipt.Loyalty_FirstName__c = (String)jsonMap.get('loyaltyFName');
        objCustomerEReceipt.Loyalty_LastName__c = (String)jsonMap.get('loyaltyLName');
        objCustomerEReceipt.Loyalty_Email__c = (String)jsonMap.get('loyaltyEmail');
        objCustomerEReceipt.Loyalty_MobilePhoneNumber__c = (String)jsonMap.get('mobilePhoneNumber');
        objCustomerEReceipt.Loyalty_Type__c = (String)jsonMap.get('loyaltyType');
        
        
        
        
        // Tax details
        List<Tax__c> listTaxRec = new List<Tax__c>();
        List<Object> listTax = (List<Object>) jsonMap.get('tax');
        
        for(object objTax : listTax ){
            Map<String,object> maptaxJSON = (Map<String,object>)objTax;
            Tax__c objtaxRec = new Tax__c();
            objtaxRec.TaxID__c = (String)maptaxJSON.get('id');
            objtaxRec.Tax_Description__c = (String)maptaxJSON.get('description');
            objtaxRec.Tax_DisplayCode__c = (String)maptaxJSON.get('displayCode');
            objtaxRec.Tax_Indicator__c = (String)maptaxJSON.get('indicator');
            objtaxRec.Tax_Type__c = 'tax'; 
            objtaxRec.Tax_Total__c = (String)maptaxJSON.get('total');         
            listTaxRec.add(objtaxRec);
        }
        
        List<Object> listVATTax = (List<Object>) jsonMap.get('totalVAT');
        for(object objTax : listVATTax ){
            Map<String,object> maptaxJSON = (Map<String,object>)objTax;
            Tax__c objtaxRec = new Tax__c();
            objtaxRec.TaxID__c = (String)maptaxJSON.get('id');
            objtaxRec.Tax_Description__c = (String)maptaxJSON.get('description');
            objtaxRec.Tax_DisplayCode__c = (String)maptaxJSON.get('displayCode');
            objtaxRec.Tax_Indicator__c = (String)maptaxJSON.get('indicator');
            objtaxRec.Tax_Type__c = 'totalVAT';    
            objtaxRec.Tax_Total__c = (String)maptaxJSON.get('total');         
            listTaxRec.add(objtaxRec);
        }
        
        
        
        
        //objCustomerEReceipt.DiscountTotal__c = (String)maptaxJSON.get('discountTotal');
        
        
        
        
        //Payment List
        Map<String,object> mapPaymentJson = (Map<String,object>)jsonMap.get('payments');
        if(mapPaymentJson != null && mapPaymentJson.containsKey('debit') != null){
            List<Object> listCredits = (List<Object>) mapPaymentJson.get('debit');
            for(object objdebit : listCredits ){
                Map<String,object> mapDebit = (Map<String,object>)objdebit;
                objCustomerEReceipt.CreditCard_Description__c = (String)mapDebit.get('cardDescription');
            }
        }
        
        
        //Cash
        if(mapPaymentJson != null && mapPaymentJson.containsKey('cash') != null){
            List<Object> listCash = (List<Object>) mapPaymentJson.get('cash');
            for(object objCash : listCash ){
                Map<String,object> mapCash = (Map<String,object>)objCash ;
                objCustomerEReceipt.Cash_Amount__c = (String)mapCash.get('amount');
                
            }
        }
        
        
        listCustomerEReceipt.add(objCustomerEReceipt);
        List<TransactionItem__c> listtransInsert = new List<TransactionItem__c >();
        List<object> listTransactionJson = (List<Object>)jsonMap.get('tranItems');
        for(object objPromotion : listTransactionJson ){
            TransactionItem__c objTransactionItem = new TransactionItem__c();
            
            //UnderTransactionItem mapping 
            Map<String,object> mapPromotions = (Map<String,object>)objPromotion;
            //itemType //paidFlag//rrpPrice//amount
            
            ////tender Detail Values for Mapping 
            Map<String,object> maptenderDetail = (Map<String,object>)mapPromotions.get('tenderDetails');
            
            
            
            //Product Values for Mapping 
            Map<String,object> mapProduct = (Map<String,object>)mapPromotions.get('product');
            if(mapProduct  != null){
                objTransactionItem.Transaction_Sku__c  = (String)mapProduct.get('sku');
                objTransactionItem.Transaction_Description__c = (String)mapProduct.get('description');
                objTransactionItem.Transaction_Barcode__c = (String)mapProduct.get('barcode');
                objTransactionItem.Transaction_Barcode__c = (String)mapProduct.get('barcode');
                objTransactionItem.Transaction_ItemName__c = (String)mapProduct.get('name');
                //PropertiesJason
                Map<String,Object> mappropertiesJson = (Map<String,Object>)mapProduct.get('propertiesJson');
                
                //Products data
                Map<String,Object> mapproducts = (Map<String,Object>)mappropertiesJson.get('products');
                //maxNoOfDiscounts = (String)mapproducts.get('maxNoOfDiscounts');
            }
            
            
            // Map<String,object> mapProductwithProduct = (Map<String,object>)mapProducts.get('products');
            
            
            
            List<object> listPromotions = (List<object>)mapPromotions.get('promotions');
            if(listPromotions  != null){
                for(object objpromotionVal :  listPromotions ){
                    Map<String,object> mapPromotionsval = (Map<String,object>)objpromotionVal;
                    object promoutinValObj = (object)mapPromotionsval.get('amount');
                    if(String.valueOf(promoutinValObj ) != '' && String.valueOf(promoutinValObj ).contains('$')){
                        message = String.valueOf(promoutinValObj );
                        //objTransactionItem.amount__c = String.valueOf(promoutinValObj);
                        objTransactionItem.Transaction_ProductType__c = (String)mapPromotionsval.get('productType');
                        // objTransactionItem.Transaction_Sku__c = objTrans.sku;
                        // objTransactionItem.Transaction_Barcode__c = objTrans.barcode;
                        // objTransactionItem.Transaction_Description__c = objTrans.description;
                        //Do all the mapping of transaction item field.
                    }else{
                        Map<String,object> mapPromotionsvalFinal = (Map<String,object>)promoutinValObj;    
                    }
                    
                }
            }
            listtransInsert.add(objTransactionItem);  
        }
        
        if(!listTaxRec.isEmpty())
            Insert listTaxRec ;
            
            
        if(!listtransInsert.isEmpty()){
            Insert listtransInsert ;
        }
        
        if(!listCustomerEReceipt.isEmpty()){
            Insert listCustomerEReceipt;
        }
        
        
        //update trans 
        List<TransactionItem__c> listtransupdate = new List<TransactionItem__c >();    
        for(TransactionItem__c  objTrans : listtransInsert ){
            objTrans.E_Receipts_Number__c = listCustomerEReceipt[0].ID;
            listtransupdate.add(objTrans);
        }
        if(!listtransupdate.isEmpty()){
            update listtransupdate;
        }
        
        List<Tax__c> listTaxdate = new List<Tax__c>();    
        for(Tax__c objTax : listTaxRec ){
            objTax.Customer_E_Receipts__c= listCustomerEReceipt[0].ID;
            listTaxdate.add(objTax);
        }
        
        if(!listTaxdate.isEmpty()){
            update listTaxdate;
        }
        
        if(!listtransupdate.isEmpty()){
            update listtransupdate;
        }
        
        listCustomerEReceipt[0].SendData__c = true;
        update listCustomerEReceipt;
        }
        catch(Exception ex) {
            message =ex.getMessage();
        }
        return message ; 
    }
    
    
    
    
}