src/objects/Customer_PromoCodes__c.object
<CustomObject>
    <fields>
        <fullName>Agent_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_PromoCodes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Display_PromoCode__c</fullName>
        <label>Display PromoCode</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promo_Code_Type__c</fullName>
        <label>Promo Code Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>11111</fullName>
                </value>
                <value>
                    <fullName>22222</fullName>
                </value>
                <value>
                    <fullName>33333</fullName>
                </value>
                <value>
                    <fullName>44444</fullName>
                </value>
                <value>
                    <fullName>55555</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer PromoCode</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Customer PromoCodes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer PromoCodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Lookup.cls
public class Lookup {

    /**
     * Returns JSON of list of ResultWrapper to Lex Components
     * @objectName - Name of SObject
     * @fld_API_Text - API name of field to display to user while searching
     * @fld_API_Val - API name of field to be returned by Lookup COmponent
     * @lim   - Total number of record to be returned
     * @fld_API_Search - API name of field to be searched
     * @searchText - text to be searched
     * */
    
    @AuraEnabled        
    public static List<String> getPickListValuesIntoList(String objectType, String selectedField){
        List<String> pickListValuesList = new List<String>();
        Schema.SObjectType convertToObj = Schema.getGlobalDescribe().get(objectType);
        Schema.DescribeSObjectResult res = convertToObj.getDescribe();
        Schema.DescribeFieldResult fieldResult = res.fields.getMap().get(selectedField).getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
        }     
        return pickListValuesList;
    }
    
    @AuraEnabled        
    public static String getCouponCodeVal(String userId,String couponType){
        System.debug('couponType'+couponType);
        System.debug('userId'+userId);
        String couponCode =  [Select Id,Name,Agent_Name__c,Promo_Code_Type__c,Display_PromoCode__c from Customer_PromoCodes__c Where Promo_Code_Type__c=:couponType
                              and Agent_Name__c =:userId limit 1].Display_PromoCode__c;
        
        return couponCode;
    }
    
    @AuraEnabled        
    public static String createCouponCode(String objVal){
        Customer_PromoCodes__c objCustomerPromo = new Customer_PromoCodes__c();
        //objCustomerPromo.
        Insert objCustomerPromo;
        return 'Success';
    }
    
    
    @AuraEnabled (cacheable=true)
    public static String searchDB(String objectName, String fld_API_Text, String fld_API_Val, 
                                  Integer lim,String fld_API_Search,String searchText ){
        
        searchText='\'%' + String.escapeSingleQuotes(searchText.trim()) + '%\'';

        
        String query = 'SELECT '+fld_API_Text+' ,'+fld_API_Val+
            			' FROM '+objectName+
            				' WHERE '+fld_API_Search+' LIKE '+searchText+ 
            			' LIMIT '+lim;
        
        List<sObject> sobjList = Database.query(query);
        List<ResultWrapper> lstRet = new List<ResultWrapper>();
        
        for(SObject s : sobjList){
            ResultWrapper obj = new ResultWrapper();
            obj.objName = objectName;
            obj.text = String.valueOf(s.get(fld_API_Text)) ;
            obj.val = String.valueOf(s.get(fld_API_Val))  ;
            lstRet.add(obj);
        } 
         return JSON.serialize(lstRet) ;
    }
    
    public class ResultWrapper{
        public String objName {get;set;}
        public String text{get;set;}
        public String val{get;set;}
    }
}