src/objects/Customer_E_Receipts__c.object
<CustomObject>
    <fields>
        <fullName>Barcode__c</fullName>
        <label>Barcode</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BusinessCheck_Amount__c</fullName>
        <description>Amount defines the total price or amount customer owes the business.</description>
        <label>BusinessCheck Amount</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cash_Amount__c</fullName>
        <description>Amount defines the total price or amount customer owes the business.</description>
        <label>Cash Amount</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cash_Type__c</fullName>
        <label>Cash Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cashier_userFirstName__c</fullName>
        <description>User first name</description>
        <label>Cashier userFirstName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cashier_userId__c</fullName>
        <description>UserId of the user that completed this action (cashier)</description>
        <label>Cashier userId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cashier_userName__c</fullName>
        <description>Username of the user that completed this action (cashier)</description>
        <label>Cashier userName</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Amount__c</fullName>
        <description>Amount defines the total price or amount customer owes the business.</description>
        <label>Change Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Check_Amount__c</fullName>
        <description>Amount defines the total price or amount customer owes the business.</description>
        <label>Check Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <formula>IF(ISBLANK(CustomerEmail__c), nonLoyaltyEmail__c, CustomerEmail__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StoreId__c</fullName>
        <description>StoreId for Store</description>
        <label>StoreId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store_Name__c</fullName>
        <description>Store Name</description>
        <label>Store Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalAmount__c</fullName>
        <label>TotalAmount</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TransactionId__c</fullName>
        <label>TransactionId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tranNo__c</fullName>
        <label>tranNo</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tranTypeId__c</fullName>
        <label>tranTypeId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Customer E-Receipts</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>E-Receipts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer E-Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Marketing_Cloud_End_Point_URL__mdt.object
<CustomObject>
    <fields>
        <fullName>End_Point__c</fullName>
        <label>End Point</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Marketing Cloud End Point URL</label>
    <pluralLabel>Marketing Cloud End Point URLs</pluralLabel>
</CustomObject>

src/objects/Marketing_Cloud_EReceipt__mdt.object
<CustomObject>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Marketing Cloud EReceipt</label>
    <pluralLabel>Marketing Cloud EReceipts</pluralLabel>
</CustomObject>

src/objects/Marketing_Cloud_Field_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>All_Taxes__c</fullName>
        <label>All Taxes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CustomEreceiptMapping__c</fullName>
        <label>CustomEreceiptMapping</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Field_Mapping__c</fullName>
        <label>Field Mapping</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Marketing Cloud Field Mapping</label>
    <pluralLabel>Marketing Cloud Field Mappings</pluralLabel>
</CustomObject>

src/objects/Tax__c.object
<CustomObject>
    <fields>
        <fullName>Customer_E_Receipts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer E-Receipts</label>
        <referenceTo>Customer_E_Receipts__c</referenceTo>
        <relationshipLabel>Taxes</relationshipLabel>
        <relationshipName>Taxes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <formula>Customer_E_Receipts__r.Email_Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaxID__c</fullName>
        <label>TaxID</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Tax_Description__c</fullName>
        <label>Tax Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_DisplayCode__c</fullName>
        <label>Tax DisplayCode</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Indicator__c</fullName>
        <label>Tax Indicator</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Total__c</fullName>
        <label>Tax Total</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Type__c</fullName>
        <label>Tax Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tax</fullName>
                </value>
                <value>
                    <fullName>NetTax</fullName>
                </value>
                <value>
                    <fullName>TaxExempt</fullName>
                </value>
                <value>
                    <fullName>TotalVAT</fullName>
                </value>
                <value>
                    <fullName>TotalAddOnVAT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tax</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Tax Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TransactionItem__c.object
<CustomObject>
    <fields>
        <fullName>E_Receipts_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>E-Receipts Number</label>
        <referenceTo>Customer_E_Receipts__c</referenceTo>
        <relationshipLabel>TransactionItems</relationshipLabel>
        <relationshipName>TransactionItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <formula>E_Receipts_Number__r.Email_Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promotions_Name__c</fullName>
        <description>Name of the promotion</description>
        <label>Promotions Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Transaction_Barcode__c</fullName>
        <description>Product barcode associated with the SKU</description>
        <label>Transaction Barcode</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_ProductType__c</fullName>
        <label>Transaction ProductType</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Quantity__c</fullName>
        <description>Quantity of the product</description>
        <label>Transaction Quantity</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Sku__c</fullName>
        <description>Product SKU</description>
        <label>Transaction Sku</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>TransactionItem</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>TransactionItem Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TransactionItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sendRequestToMarketingCloud.cls
public class sendRequestToMarketingCloud {

 
    static final Map<String,String> mapClientIdSecretToValue =  getClientSecretKeyToValue();
    static final Map<String,String> mapmarkeingCloudEndpointNameToValue =  getEndPointNameToValue();
    static final String accessToken = sendRequestForAccessToken();
    static final String accessTokenval = 'AccessToken'; 
    static final String triggerSend = 'TriggerSend';
    
    //Get Cient Secret Key and Value 
    private static Map<String,String> getEndPointNameToValue(){
        Map<String,String> tempMapClientIdSecretToValue =  new Map<String,String>();
        for(Marketing_Cloud_End_Point_URL__mdt objMarketing : [SELECT Id,MasterLabel,End_Point__c from Marketing_Cloud_End_Point_URL__mdt]){
            tempMapClientIdSecretToValue.put(objMarketing.MasterLabel,objMarketing.End_Point__c );
        }
        return tempMapClientIdSecretToValue;
    }
    
   @future(callout=true)
    public static void sendCustomerEReceipt(Set<Id> customerEreceiptId){
        System.debug('=========='+accessToken);
        List<Sobject> listTransactionItems = getCustomerEreceiptInfo(customerEreceiptId); 
        List<Sobject> listTransactionItems1 = getTransactionList(customerEreceiptId); 
        List<Sobject> listTransactionItems3 = getTaxInfo(customerEreceiptId);
        try {
            sendRequestForDataExtension1(accessToken,listTransactionItems,'CustomerEReceipt'); 
            sendRequestForDataExtension1(accessToken,listTransactionItems1 ,'TransactionItem');
            sendRequestForDataExtension1(accessToken,listTransactionItems3 ,'Tax');
            sendRequestForTriggerSend(accessToken,listTransactionItems);
        } 
       catch(System.CalloutException e) {
            System.debug('Callout error: '+ e);
        }
    }
    
    
    
    public static Void sendRequestForDataExtension1(String accessToken,List<Sobject> tempListCustomerEReceipt,String dataExtensionType){
        JSONGenerator gen = JSON.createGenerator(true);
        gen = generateJasonFortransactionDataExtension(gen,tempListCustomerEReceipt,dataExtensionType);
        System.debug('==dataextension==='+gen.getAsString());
        HttpRequest req = new HttpRequest();
        HttpResponse res = new HttpResponse();
        Http http = new Http();
        if(dataExtensionType == 'CustomerEReceipt'){
        req.setEndpoint(mapmarkeingCloudEndpointNameToValue.get(dataExtensionType));
        }
        else if (dataExtensionType == 'TransactionItem'){
        req.setEndpoint(mapmarkeingCloudEndpointNameToValue.get(dataExtensionType));
        }
        else{
        req.setEndpoint(mapmarkeingCloudEndpointNameToValue.get(dataExtensionType));
        }
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json'); 
        req.setHeader('Authorization', 'Bearer '+ accessToken); 
        req.setBody(gen.getAsString());
        req.setCompressed(true);
        res = http.send(req);
        system.debug('========='+res);
        //if(!Test.isRunningTest())
         //   List<SObject> listSobject = (List<SObject> )JSON.deserializeUntyped(res.getBody());
        
    } 
    
    @testVisible
    private static JSONGenerator generateJasonFortransactionDataExtension(JSONGenerator gen,List<Sobject> tempListCustomerEReceipt, String dataExtensiontype){
        gen.writeStartArray();
        for(Sobject objTransaction : tempListCustomerEReceipt){
            gen.writeStartObject();
            gen.writeFieldName('keys');
            gen.writeStartObject();       
          //  gen.writeObjectField('Skunumber', objTransaction.Sku__c);
            gen.writeEndObject();
            gen.writeFieldName('values');
            gen.writeStartObject();
            Map<String, String>dataMap=getJsonMap(objTransaction,dataExtensiontype);
            for (String key:dataMap.keySet()) {
               if(dataMap.get(key) != null)
               gen.writeObjectField(key, dataMap.get(key));
               else
               gen.writeObjectField(key, '');
               
                
            }
            gen.writeEndObject();
            gen.writeEndObject(); 
        }
        gen.writeEndArray();
        return gen;
    }
    
    private static Map<String, String> getJsonMap(Sobject objTransaction,String DataExtensionType) {
        System.debug('======DataExtensionType ======='+DataExtensionType );
        Map<String,String> mapObjectnameToObjectAPI = new Map<String,String>();
        if(DataExtensionType == 'CustomerEReceipt'){
            mapObjectnameToObjectAPI = getFieldList('Customer_E_Receipts__c');
        }
        else if (DataExtensionType == 'TransactionItem'){
            mapObjectnameToObjectAPI = getFieldList('TransactionItem__c');
        }  
        else{
            mapObjectnameToObjectAPI = getFieldList('Tax__c');
        }    
        set<string> setApiName = new Set<String>();
        setApiName.addAll(mapObjectnameToObjectAPI.keyset());
        
        system.debug('=====setApiName=====>'+setApiName);
        
        Marketing_Cloud_Field_Mapping__mdt objMarketingCloudFieldMapping = getMarketingCloudFieldMapping();
        Map<String, Object> meta = new  Map<String, Object>();
        if(DataExtensionType == 'CustomerEReceipt'){
            meta = (Map<String, Object>) JSON.deserializeUntyped(objMarketingCloudFieldMapping.CustomEreceiptMapping__c);
        }
        else if(DataExtensionType == 'TransactionItem'){
            meta = (Map<String, Object>) JSON.deserializeUntyped(objMarketingCloudFieldMapping.Field_Mapping__c); 
        }
        else {
            meta = (Map<String, Object>) JSON.deserializeUntyped(objMarketingCloudFieldMapping.All_Taxes__c); 
        } 
        System.debug('====meta ======'+meta );
        Map<String, String> dataMap = new Map<String, String>();
        for(String objMetaDataMap : meta.Keyset()){
            String fieldApi = (String)meta.get(objMetaDataMap);
            if(setApiName.contains(fieldApi.toLowerCase()))
                dataMap.put(objMetaDataMap ,  (String)objTransaction.get(fieldApi) );
            else
                dataMap.put(objMetaDataMap ,  (String)objTransaction.getSobject('E_Receipts_Number__r').get(fieldApi) );
                
        }
        
        system.debug('======='+ dataMap );
        System.debug(LoggingLevel.Info, 'Your info');
        return dataMap;
        
    } 
    
    
    
    
     //Get Transaction List
    private static List<Sobject> getCustomerEreceiptInfo(Set<Id> customerEreceiptId){
        List<Sobject> listCustomerReceipt = [SELECT Id,Barcode__c,BusinessCheck_Amount__c,Cash_Amount__c,Cashier_userFirstName__c,
                                                Cashier_userId__c,tranNo__c,tranTypeId__c,Cashier_userName__c,Email_Address__c,Cash_Type__c,Change_Amount__c,Check_Amount__c,
                                                TransactionId__c
                                                FROM Customer_E_Receipts__c WHERE ID IN : customerEreceiptId];
        return listCustomerReceipt;
    }
    
    //Get Transaction List
    private static List<Sobject> getTransactionList(Set<Id> tempTransactionId){
        List<Sobject> listTransactionItems = [SELECT Id,Transaction_Sku__c,Transaction_ProductType__c,Transaction_Barcode__c,Transaction_Quantity__c,E_Receipts_Number__r.Name, E_Receipts_Number__r.Email_Address__c,
                                                         E_Receipts_Number__r.StoreId__c,Email_Address__c, E_Receipts_Number__r.Store_Name__c, E_Receipts_Number__r.TotalAmount__c, Promotions_Name__c  
                                                         FROM TransactionItem__c WHERE E_Receipts_Number__c IN : tempTransactionId];
        return listTransactionItems;
    }
    
    //Get Transaction List
    private static List<Sobject> getTaxInfo(Set<Id> tempTransactionId){
        List<Sobject> listTransactionItems = [SELECT Id,Tax_Description__c,Tax_DisplayCode__c,TaxID__c,Tax_Indicator__c,
                                                Tax_Total__c,Tax_Type__c,Email_Address__c
                                             from Tax__c WHERE Customer_E_Receipts__c IN : tempTransactionId];
        return listTransactionItems;
    }
    
    
    
    //Get ClientID, Client Secret Key and Value 
    private static Map<String,String> getClientSecretKeyToValue(){
        Map<String,String> tempMapClientIdSecretToValue =  new Map<String,String>();
        for(Marketing_Cloud_EReceipt__mdt objMarketing : [SELECT Id,MasterLabel,Key__c from Marketing_Cloud_EReceipt__mdt]){
            tempMapClientIdSecretToValue.put(objMarketing.MasterLabel,objMarketing.Key__c);
        }
        return tempMapClientIdSecretToValue;
    }

   
    public static String sendRequestForAccessToken(){
        String tempAccessToken;
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject(); 
        for(String objClientIdSecret : mapClientIdSecretToValue.keySet()){
            gen.writeObjectField(objClientIdSecret, mapClientIdSecretToValue.get(objClientIdSecret));    
        }
        gen.writeEndObject();
        HttpRequest req = new HttpRequest();
        HttpResponse res = new HttpResponse();
        Http http = new Http();
        req.setEndpoint(mapmarkeingCloudEndpointNameToValue.get(accessTokenval));
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');  
        req.setBody(gen.getAsString());
        req.setCompressed(true);
        res = http.send(req);
        Map<String, Object> meta = (Map<String, Object> )JSON.deserializeUntyped(res.getBody());
        tempAccessToken = (String)meta.get('accessToken');
        return tempAccessToken;
    }  
    
    public static Void sendRequestForTriggerSend(String accessToken,List<Sobject> templistTransactionItems){
        Sobject objTransactionItem = templistTransactionItems[0];
        String emailAdd = String.valueOf(objTransactionItem.getSObject('E_Receipts_Number__r').get('Email_Address__c'));
        String firstName = String.valueOf(objTransactionItem.getSObject('E_Receipts_Number__r').get('Email_Address__c'));
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeFieldName('From');
        gen.writeStartObject();       
        gen.writeObjectField('Address',emailAdd );
        gen.writeObjectField('Name', emailAdd);
        gen.writeEndObject();
        gen.writeFieldName('To');
        gen.writeStartObject();       
        gen.writeObjectField('Address', emailAdd);
        gen.writeObjectField('SubscriberKey', emailAdd);
        gen.writeFieldName('ContactAttributes');
        gen.writeStartObject(); 
        gen.writeFieldName('SubscriberAttributes');
        gen.writeStartObject();       
        gen.writeObjectField('First Name', firstName);
        gen.writeObjectField('Last Name', firstName);
        gen.writeEndObject();
        gen.writeEndObject();
        gen.writeEndObject();
        gen.writeFieldName('Options');
        gen.writeStartObject();       
        gen.writeObjectField('RequestType', 'SYNC');
        gen.writeEndObject();
        System.debug('==TriggerSend==='+gen.getAsString());
        HttpRequest req = new HttpRequest();
        HttpResponse res = new HttpResponse();
        Http http = new Http();
        req.setEndpoint(mapmarkeingCloudEndpointNameToValue.get(triggerSend));
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json'); 
        req.setHeader('Authorization', 'Bearer '+ accessToken); 
        req.setBody(gen.getAsString());
        req.setCompressed(true);
        res = http.send(req);
        System.debug('===res======='+res);
    }   
    
    
    public static map<string, string> getFieldList(String selectedSObject){
    
        map<string, string> fieldList = new map<string, string>();
        if(selectedSObject != null){
            map<string,SObjectField> fList = schema.getGlobalDescribe().get(selectedSObject).getDescribe().fields.getMap();
            for(string str: fList.keySet()){
                fieldList.put(str, fList.get(str).getDescribe().getLabel());                
            }
        }else{
            return null;
        }
        return fieldList;
    }
    
    public Static Marketing_Cloud_Field_Mapping__mdt getMarketingCloudFieldMapping(){
        return [select Label,CustomEreceiptMapping__c,Field_Mapping__c,All_Taxes__c from  Marketing_Cloud_Field_Mapping__mdt Limit 1];
    }
    
}