src/objects/Ideas_That_Work__c.object
<CustomObject>
    <fields>
        <fullName>Are_there_other_brands_currently_20__c</fullName>
        <label>Are there other brands currently -20</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Please Select</fullName>
                    <default>true</default>
                    <label>Please Select</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Not Sure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Carhartt_currently_offering_your_idea__c</fullName>
        <label>Carhartt currently offering your idea?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Please Select</fullName>
                    <default>true</default>
                    <label>Please Select</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Not Sure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Do_you_have_any_information_regarding_co__c</fullName>
        <label>Do you have any information regarding co</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Not Sure</fullName>
                </value>
                <value>
                    <fullName>Please Select</fullName>
                    <default>true</default>
                    <label>Please Select</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Idea_Category__c</fullName>
        <label>Idea Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Idea</fullName>
                </value>
                <value>
                    <fullName>Packaging Idea</fullName>
                </value>
                <value>
                    <fullName>Marketing/Advertising Idea</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Please Select</fullName>
                    <default>true</default>
                    <label>Please Select</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Information_regarding_copyrights_22__c</fullName>
        <label>Information regarding copyrights -22</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Please Select</fullName>
                    <default>true</default>
                    <label>Please Select</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TermCondition__c</fullName>
        <defaultValue>true</defaultValue>
        <label>TermCondition</label>
        <type>Checkbox</type>
    </fields>
    <label>Ideas That Work</label>
    <nameField>
        <displayFormat>Idea-{0000}</displayFormat>
        <label>Ideas That Work Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ideas That Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactIdeaControllerTest.cls
@isTest
public class ContactIdeaControllerTest{

    @isTest static void testGetStatements() {
       
            ContactIdeaController.getStatements();
    }
    
    @isTest static void testCreateIdea() {
        Ideas_That_Work__c objIdea = new Ideas_That_Work__c();
        Insert objIdea;
        String IdeaVal = '{"IsDeleted":false,"TermCondition__c":true,"OwnerId":"0050h000003nIqRAAU","Are_there_other_brands_currently_20__c":"Please Select","Information_regarding_copyrights_22__c":"Please Select","Do_you_have_any_information_regarding_co__c":"Please Select","Carhartt_currently_offering_your_idea__c":"Please Select","Idea_Category__c":"Please Select","Email__c":"asasa@gmail.com"}';
        ContactIdeaController.createIdea(IdeaVal,'','Insert');

        String IdeaVal1 = '{"IsDeleted":false,"TermCondition__c":true,"OwnerId":"0050h000003nIqRAAU","Are_there_other_brands_currently_20__c":"Please Select","Information_regarding_copyrights_22__c":"Please Select","Do_you_have_any_information_regarding_co__c":"Please Select","Carhartt_currently_offering_your_idea__c":"Please Select","Idea_Category__c":"Please Select","Email__c":"asasa@gmail.com"}';
        ContactIdeaController.createIdea(IdeaVal,objIdea.Id,'Update');
    }
    
    
}